spring:

  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:h2:mem:testdb;mode=mysql
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always
      data-locations: classpath:init-data.sql
      schema-locations: classpath:init-schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none

  logging:
    level:
      org:
        hibernate:
          SQL: debug
          type: trace
